# Copyright (C), 2008-2030, OPLUS Mobile Comm Corp., Ltd
### All rights reserved.
###
### File: - OplusKernelEnvConfig.mk
### Description:
###     you can get the oplus feature variables set in android side in this file
###     this file will add global macro for common oplus added feature
###     BSP team can do customzation by referring the feature variables
### Version: 1.0
### Date: 2020-03-18
### Author: Liang.Sun
###
### ------------------------------- Revision History: ----------------------------
### <author>                        <date>       <version>   <desc>
### ------------------------------------------------------------------------------
##################################################################################

-include oplus_native_features.mk

###ifdef OPLUS_ARCH_INJECT
OPLUS_CONNECTIVITY_NATIVE_FEATURE_SET :=


ifeq ($(OPLUS_FEATURE_WIFI_MTUDETECT), yes)
OPLUS_CONNECTIVITY_NATIVE_FEATURE_SET += OPLUS_FEATURE_WIFI_MTUDETECT
endif

$(foreach myfeature,$(OPLUS_CONNECTIVITY_NATIVE_FEATURE_SET),\
    $( \
        $(eval KBUILD_CFLAGS += -D$(myfeature)) \
        $(eval KBUILD_CPPFLAGS += -D$(myfeature)) \
        $(eval CFLAGS_KERNEL += -D$(myfeature)) \
        $(eval CFLAGS_MODULE += -D$(myfeature)) \
    ) \
)
###endif OPLUS_ARCH_INJECT

ALLOWED_MCROS :=  \
OPLUS_FEATURE_STORAGE_TOOL  \
OPLUS_FEATURE_UFS_DRIVER  \
OPLUS_FEATURE_UFS_SHOW_LATENCY \
OPLUS_FEATURE_UFSPLUS  \
OPLUS_FEATURE_EMMC_SDCARD_OPTIMIZE  \
OPLUS_FEATURE_EMMC_DRIVER  \
OPLUS_FEATURE_CHG_BASIC  \
OPLUS_FEATURE_CONNFCSOFT  \
OPLUS_FEATURE_AGINGTEST  \
OPLUS_FEATURE_SENSOR_SMEM  \
OPLUS_FEATURE_SSR  \
OPLUS_FEATURE_TP_BASIC  \
OPLUS_FEATURE_WIFI_SLA  \
OPLUS_FEATURE_DUMPDEVICE  \
OPLUS_FEATURE_WIFI_MTUDETECT  \
OPLUS_FEATURE_XTOWNER_INPUT  \
OPLUS_FEATURE_PW_4096  \
OPLUS_FEATURE_PXLW_IRIS5  \
OPLUS_FEATURE_MULTI_FREEAREA  \
OPLUS_FEATURE_VIRTUAL_RESERVE_MEMORY  \
OPLUS_FEATURE_GPU_MINIDUMP  \
OPLUS_FEATURE_AUDIO_FTM \
OPLUS_FEATURE_SPEAKER_MUTE \
OPLUS_FEATURE_MI2S_SLAVE \
OPLUS_FEATURE_KTV \
OPLUS_FEATURE_MUTE_DETECT \
OPLUS_FEATURE_EXFAT_SUPPORT \
OPLUS_FEATURE_SDCARDFS_SUPPORT \
OPLUS_FEATURE_CAMERA_OIS  \
OPLUS_FEATURE_SAU  \
OPLUS_FEATURE_MM_FEEDBACK \
CONFIG_OPLUS_FEATURE_MM_FEEDBACK \
OPLUS_BUG_COMPATIBILITY \
OPLUS_BUG_STABILITY \
OPLUS_BUG_DEBUG \
OPLUS_ARCH_INJECT \
OPLUS_ARCH_EXTENDS \
VENDOR_EDIT \
OPLUS_FEATURE_CAMERA_COMMON \
OPLUS_FEATURE_ADSP_RECOVERY \
OPLUS_FEATURE_MODEM_MINIDUMP \
OPLUS_FEATURE_WIFI_DUALSTA_AP_BLACKLIST

$(foreach myfeature,$(ALLOWED_MCROS),\
         $(warning make $(myfeature) to be a macro here) \
         $(eval KBUILD_CFLAGS += -D$(myfeature)) \
         $(eval KBUILD_CPPFLAGS += -D$(myfeature)) \
         $(eval CFLAGS_KERNEL += -D$(myfeature)) \
         $(eval CFLAGS_MODULE += -D$(myfeature)) \
)

# BSP team can do customzation by referring the feature variables

ifeq ($(OPLUS_FEATURE_AOD_RAMLESS),yes)
KBUILD_CFLAGS += -DOPLUS_FEATURE_AOD_RAMLESS
KBUILD_CPPFLAGS += -DOPLUS_FEATURE_AOD_RAMLESS
CFLAGS_KERNEL += -DOPLUS_FEATURE_AOD_RAMLESS
CFLAGS_MODULE += -DOPLUS_FEATURE_AOD_RAMLESS
endif

ifeq ($(OPLUS_FEATURE_DP_MAX20328),yes)
KBUILD_CFLAGS += -DOPLUS_FEATURE_DP_MAX20328
endif

ifeq ($(OPLUS_FEATURE_FSA4480),yes)
KBUILD_CFLAGS += -DOPLUS_FEATURE_FSA4480
endif

ifeq ($(OPLUS_FEATURE_SECURE_KEVENTUPLOAD),yes)
export CONFIG_OPLUS_KEVENT_UPLOAD=y
KBUILD_CFLAGS += -DCONFIG_OPLUS_KEVENT_UPLOAD
KBUILD_CPPFLAGS += -DCONFIG_OPLUS_KEVENT_UPLOAD
CFLAGS_KERNEL += -DCONFIG_OPLUS_KEVENT_UPLOAD
CFLAGS_MODULE += -DCONFIG_OPLUS_KEVENT_UPLOAD
endif

ifeq ($(OPLUS_FEATURE_OP_SPECIFIC_AUDIO_KERNEL),yes)
KBUILD_CFLAGS += -DOPLUS_FEATURE_OP_SPECIFIC_AUDIO_KERNEL
endif

ifeq ($(OPLUS_FEATURE_MM_ULTRASOUND),yes)
export OPLUS_FEATURE_MM_ULTRASOUND=y
KBUILD_CFLAGS += -DOPLUS_FEATURE_MM_ULTRASOUND
endif

ifeq ($(OPLUS_FEATURE_ONEPLUS_MM_LIMIT_SVA_BARGIN),yes)
KBUILD_CFLAGS += -DOPLUS_FEATURE_ONEPLUS_MM_LIMIT_SVA_BARGIN
endif

ifeq ($(OPLUS_FEATURE_DUMPDEVICE),yes)
export CONFIG_OPLUS_FEATURE_DUMP_DEVICE_INFO=y
KBUILD_CFLAGS += -DCONFIG_OPLUS_FEATURE_DUMP_DEVICE_INFO
endif

ifeq ($(OPLUS_FEATURE_MM_FEEDBACK),yes)
export CONFIG_OPLUS_FEATURE_MM_FEEDBACK=y
KBUILD_CFLAGS += -DCONFIG_OPLUS_FEATURE_MM_FEEDBACK
endif


ifeq ($(OPLUS_FEATURE_BRAND_SHOW_FLAG),realme)
export CONFIG_BRAND_SHOW_FLAG=realme
KBUILD_CFLAGS += -DCONFIG_BRAND_SHOW_FLAG
endif

ifeq ($(OPLUS_FEATURE_SHIPPING_API_LEVEL),28)
export CONFIG_SHIPPING_API_LEVEL=28
KBUILD_CFLAGS += -DCONFIG_SHIPPING_API_LEVEL
endif

ifeq ($(strip $(OPLUS_FEATURE_ONEPLUS_MOTOR)), OP7)
export CONFIG_ONEPLUS_MOTOR_OP7=OP7
KBUILD_CFLAGS += -DCONFIG_ONEPLUS_MOTOR_OP7
endif


$(warning TARGET_PRODUCT:$(TARGET_PRODUCT))
ifeq ($(TARGET_PRODUCT),msmnile)
KBUILD_CFLAGS +=   -DOP_8150_ADAPT
KBUILD_CPPFLAGS += -DOP_8150_ADAPT
CFLAGS_KERNEL +=   -DOP_8150_ADAPT
CFLAGS_MODULE +=   -DOP_8150_ADAPT
export CONFIG_PROJECT_INFO=y
endif