#ifdef VENDOR_EDIT
obj-$(CONFIG_OPLUS_SYSTEM_KERNEL)    += system/
#endif /* VENDOR_EDIT */

obj-$(CONFIG_OPLUS_COMMON_SOFT)	+=  device_info/

#ifdefine OPLUS_ARCH_EXTENDS
obj-y +=  oplus_kevent_feedback/
#endif /* OPLUS_ARCH_EXTENDS */
